import { StyleProp, TextStyle } from 'react-native'

export const content-box: StyleProp<TextStyle>
export const section-title: StyleProp<TextStyle>
export const search__screen: StyleProp<TextStyle>
export const inner: StyleProp<TextStyle>
export const form-group: StyleProp<TextStyle>
export const control-label: StyleProp<TextStyle>
export const sort-by: StyleProp<TextStyle>
export const screens: StyleProp<TextStyle>
export const card-title: StyleProp<TextStyle>
export const card: StyleProp<TextStyle>
export const screen: StyleProp<TextStyle>
export const screen-info: StyleProp<TextStyle>
export const slick-current: StyleProp<TextStyle>
export const slick-slide: StyleProp<TextStyle>
export const button-row: StyleProp<TextStyle>
export const map: StyleProp<TextStyle>
export const filter__options: StyleProp<TextStyle>
export const filter__item: StyleProp<TextStyle>
export const slick-custom-arrow: StyleProp<TextStyle>
export const arrow: StyleProp<TextStyle>
export const next-arrow: StyleProp<TextStyle>
export const search-toggler: StyleProp<TextStyle>
export const hide__filters: StyleProp<TextStyle>
export const search__screen--left: StyleProp<TextStyle>
export const search__screen--right: StyleProp<TextStyle>
export const hide__filters): StyleProp<TextStyle>
export const map-screen-popup: StyleProp<TextStyle>
export const screen__top: StyleProp<TextStyle>
export const cardscreen: StyleProp<TextStyle>
export const icon: StyleProp<TextStyle>
export const sections-wrapper: StyleProp<TextStyle>
export const our__works: StyleProp<TextStyle>
export const image: StyleProp<TextStyle>
export const checkout__steps: StyleProp<TextStyle>
export const step-title: StyleProp<TextStyle>
export const steps__wrapper: StyleProp<TextStyle>
export const step-image: StyleProp<TextStyle>
export const curve: StyleProp<TextStyle>
export const top: StyleProp<TextStyle>
export const step-1: StyleProp<TextStyle>
export const step-2: StyleProp<TextStyle>
export const step-3: StyleProp<TextStyle>
export const step-4: StyleProp<TextStyle>
export const creat-account: StyleProp<TextStyle>
export const btn: StyleProp<TextStyle>
export const row: StyleProp<TextStyle>
export const about-us: StyleProp<TextStyle>
export const bg: StyleProp<TextStyle>
export const flex-wrapper: StyleProp<TextStyle>
export const detail-slider: StyleProp<TextStyle>
export const thumb-slider: StyleProp<TextStyle>
export const slide: StyleProp<TextStyle>
