import { StyleProp, TextStyle } from 'react-native'

export const svgs: StyleProp<TextStyle>
export const calendar-tooltip2: StyleProp<TextStyle>
export const head: StyleProp<TextStyle>
export const current-date: StyleProp<TextStyle>
export const icon: StyleProp<TextStyle>
export const inner-scroll: StyleProp<TextStyle>
export const btn-primarycd-add-to-cart: StyleProp<TextStyle>
export const text-replace: StyleProp<TextStyle>
export const cd-cart::before: StyleProp<TextStyle>
export const cd-cart--open::before: StyleProp<TextStyle>
export const cd-cart__content: StyleProp<TextStyle>
export const cd-cart--empty: StyleProp<TextStyle>
export const cd-cart__trigger: StyleProp<TextStyle>
export const cd-cart__trigger::before: StyleProp<TextStyle>
export const cd-cart__trigger::after: StyleProp<TextStyle>
export const cd-cart--open: StyleProp<TextStyle>
export const cd-cart__layout: StyleProp<TextStyle>
export const cd-cart__count: StyleProp<TextStyle>
export const cd-cart__body: StyleProp<TextStyle>
export const cd-cart__header: StyleProp<TextStyle>
export const cd-cart__undo: StyleProp<TextStyle>
export const cd-cart__undo--visible: StyleProp<TextStyle>
export const cd-cart__product: StyleProp<TextStyle>
export const cart__info--screen: StyleProp<TextStyle>
export const cd-cart__product--deleted: StyleProp<TextStyle>
export const cd-cart__product--deletedcd-cart__product--undo: StyleProp<TextStyle>
export const cd-cart__product--deleted+cd-cart__product: StyleProp<TextStyle>
export const cd-cart__product--undo+cd-cart__product: StyleProp<TextStyle>
export const cd-cart__image: StyleProp<TextStyle>
export const cd-cart__details: StyleProp<TextStyle>
export const cd-cart__price: StyleProp<TextStyle>
export const cd-cart__quantity: StyleProp<TextStyle>
export const cd-cart__delete-item: StyleProp<TextStyle>
export const cd-cart__delete-item:hover: StyleProp<TextStyle>
export const cd-cart__footer: StyleProp<TextStyle>
export const cd-cart__checkout: StyleProp<TextStyle>
export const cd-article-link: StyleProp<TextStyle>
export const cd-article-link:hover: StyleProp<TextStyle>
