import { StyleProp, TextStyle } from 'react-native'

export const content-wrapper: StyleProp<TextStyle>
export const bg: StyleProp<TextStyle>
export const intro: StyleProp<TextStyle>
export const blue: StyleProp<TextStyle>
export const black: StyleProp<TextStyle>
export const features: StyleProp<TextStyle>
export const container: StyleProp<TextStyle>
export const btn: StyleProp<TextStyle>
export const inner: StyleProp<TextStyle>
export const technology: StyleProp<TextStyle>
export const bg-bottom: StyleProp<TextStyle>
export const show-on-767: StyleProp<TextStyle>
export const companies: StyleProp<TextStyle>
export const solutions: StyleProp<TextStyle>
export const solution: StyleProp<TextStyle>
export const section-2: StyleProp<TextStyle>
export const bg-3: StyleProp<TextStyle>
export const red: StyleProp<TextStyle>
export const white: StyleProp<TextStyle>
export const bg-4: StyleProp<TextStyle>
export const bottom-section: StyleProp<TextStyle>
export const left: StyleProp<TextStyle>
export const right: StyleProp<TextStyle>
export const image: StyleProp<TextStyle>
export const note: StyleProp<TextStyle>
export const contact-form: StyleProp<TextStyle>
export const btn-primary: StyleProp<TextStyle>
export const form-group: StyleProp<TextStyle>
export const form-control: StyleProp<TextStyle>
export const phone-number: StyleProp<TextStyle>
export const country-picker: StyleProp<TextStyle>
export const phone-input: StyleProp<TextStyle>
export const select2-container: StyleProp<TextStyle>
export const select2-selection--single: StyleProp<TextStyle>
export const select2-container--default: StyleProp<TextStyle>
export const select2-selection__rendered: StyleProp<TextStyle>
export const select2-selection__arrow: StyleProp<TextStyle>
export const select2-results__option[aria-selected]: StyleProp<TextStyle>
export const features__row: StyleProp<TextStyle>
export const features__row--image: StyleProp<TextStyle>
export const features__row--copy: StyleProp<TextStyle>
export const pink: StyleProp<TextStyle>
export const flex-row: StyleProp<TextStyle>
export const copyright: StyleProp<TextStyle>
export const solution__row: StyleProp<TextStyle>
export const solution__row--copy: StyleProp<TextStyle>
export const solution__row--image: StyleProp<TextStyle>
export const slick-arrow: StyleProp<TextStyle>
export const slick-arrowslick-prev: StyleProp<TextStyle>
